# Generated by Django 5.1 on 2024-08-31 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transacton',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
                ('type', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='child', to='transactions.transacton')),
            ],
        ),
    ]
