# Generated by Django 5.1 on 2024-08-31 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transacton',
            new_name='Transaction',
        ),
    ]
