# Generated by Django 5.1 on 2024-08-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_transaction_sum_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_sum',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
