# Generated by Django 5.1 on 2024-08-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_transaction_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_sum',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
